apiVersion: apps/v1
kind: Deployment
metadata:
  name: nothing-gpt-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nothing-gpt-ui
  template:
    metadata:
      labels:
        app: nothing-gpt-ui
    spec:
      containers:
        - name: ui
          image: us-central1-docker.pkg.dev/nothing-gpt/nothing-gpt/ui:latest
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
          ports:
            - containerPort: 8000
          env:
            - name: SERVE_URL
              value: http://nothing-gpt-serve:8000/v1
          readinessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: nothing-gpt-ui
spec:
  type: LoadBalancer
  selector:
    app: nothing-gpt-ui
  ports:
    - port: 80
      targetPort: 8000
