steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - docker/${_TARGET}.Dockerfile
      - -t
      - us-central1-docker.pkg.dev/nothing-gpt/nothing-gpt/${_TARGET}:latest
      - .
images:
  - us-central1-docker.pkg.dev/nothing-gpt/nothing-gpt/${_TARGET}:latest
substitutions:
  _TARGET: ""
